src/ci/docker/docker-compose.yml:
  content: |
    version: '3.8'
    services:
      frontend:
        build:
          context: ../../../
          dockerfile: src/ci/docker/Dockerfile
        ports:
          - "3000:3000"
        environment:
          - NODE_ENV=development
        volumes:
          - ../../../:/app
          - /app/node_modules
        env_file:
          - ../../env/.env
          - ../../env/.env.development
        depends_on:
          - backend

      backend:
        image: node:16-alpine
        volumes:
          - ../../../:/app
        working_dir: /app
        command: npm run dev:backend
        environment:
          - NODE_ENV=development
        env_file:
          - ../../env/.env
          - ../../env/.env.development

      test:
        build:
          context: ../../../
          dockerfile: src/ci/docker/Dockerfile
        volumes:
          - ../../../:/app
        command: npm run test
        env_file:
          - ../../env/.env
          - ../../env/.env.development

    networks:
      default:
        driver: bridge
  dependency:
    - src/ci/docker/Dockerfile
    - src/env/.env
    - src/env/.env.development
    - src/build/next.config.js